### ISSUE TITLE
Set up branch at "Adding a couple of utilities"

### ISSUE THREAD

**Issue by carlacfw** [test-er-8-or/tic-tac-toe#1]
Hi Charles,
I had problems with the laptop I was working with and had to do all the set up again in my old laptop.
Everything went fine until I added this piece of code (find it at set up Readme branch at "Adding a couple of utilities" part) 
`yarn add ramda ramda-adjunct styled-components react-router redux react-redux redux-observable rxjs redux-devtools-extension
yarn add -D enzyme enzyme-adapter-react-16 enzyme-to-json jest-enzyme jest-styled-components react-test-renderer redux-mock-store` 

After I installed this I did git add -A and the git commit, but then the commit failed showing the following error

`carla@~/workspace/masterclass  (master)
$ git commit -m "Add ramda, ramda-adjunct, styled-components"
husky > npm run -s precommit (node v9.11.1)

/home/carla/workspace/masterclass/node_modules/any-observable/register.js:29
		throw new Error('Cannot find any-observable implementation nor' +
		^

Error: Cannot find any-observable implementation nor global.Observable. You must install polyfill or call require("any-observable/register") with your preferred implementation, e.g. require("any-observable/register")('rxjs') on application load prior to any require("any-observable").
    at loadImplementation (/home/carla/workspace/masterclass/node_modules/any-observable/register.js:29:9)
    at register (/home/carla/workspace/masterclass/node_modules/any-observable/loader.js:32:18)
    at Object.<anonymous> (/home/carla/workspace/masterclass/node_modules/any-observable/index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)

husky > pre-commit hook failed (add --no-verify to bypass)`

After a while trying to understand what was going on, I started comparing what I had in the `package.json` and I saw that I had some of the version numbers different then the ones in the picture of your package.json (I know that you said it could happen) but then I changed for the versions that you had and it worked. I really don't know why and what exactly happened, but it was after added the piece of code I mentioned above.

Hope I could explained it properly, please tell me if its unclear...
Cheers,
Carla

**Comment by arist0cles** [comment]
Hey Carla,
I had the same problem you had, which I think is related to [version 6 of rxjs](https://github.com/okonet/lint-staged/issues/416). I got around this by installing rxjs-compat, `yarn add -D rxjs-compat` or it could be fixed by locking the version at the same as Charles used. (v5.5.10)

**Comment by carlacfw** [comment]
Hi!!
yeah I changed my version to same as Charles and it worked, but I wasnt sure if it was the best fixing. Thanks for sharing!! :)
